openapi: 3.1.0
info:
  title: getpaid API
  version: v2alpha1
  termsOfService: https://getpaid.io/terms/
  contact:
    email: support@getpaid.io
    url: https://getpaid.io/contact
  description: |
    # Introduction

    Our APIs provide programmatic access to the getpaid platform. This page contains
    a comprehensive reference for all of our public APIs. For walkthrough
    documentation please see our [main docs site](https://docs.getpaid.io).

    ## Getting Started

    To get started, sign up at <https://getpaid.io>. This will give you access to
    the [getpaid Dashboard](https://dashboard.getpaid.io) where you can configure
    your account and retrieve your credentials needed to authenticate with our APIs.

    To streamline integration we provide [client libraries](https://docs.getpaid.io)
    for a number of languages, otherwise you can integrate directly with the API
    using the HTTP tooling built-in to most modern frameworks.

    ## Fields Format

    | Type | Format |
    | :- | :- |
    | Amount Minor | Amount in the minor currency unit (e.g. 100 cents for 1 EUR). |
    | Card Number | Credit/debit card numbers are formatted as a string of digits with no white spaces or dashes. The value must be between 13 and 19 digits long and must fulfill the [Luhn check](https://en.wikipedia.org/wiki/Luhn_algorithm). |
    | Card Verification Value | Card Verification Value (CVV) or Card Verification Code (CVC) is formatted as a string of digits. The value must be 3 or 4 digits long. |
    | Country    | The country code fields follow the [ISO 3166-1 Alpha 2 standard](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2) in uppercase. Examples: `ES`, `US`.                                                    |
    | Currency   | The currency code fields follow the [ISO 4217 standard](https://en.wikipedia.org/wiki/ISO_4217) in uppercase. Examples: `EUR`, `USD`.                                                                     |
    | Date       | Dates are formatted using the complete date format according to the [ISO 8601 standard](https://www.w3.org/TR/NOTE-datetime): `YYYY-MM-DD`. Example: `2023-09-30`.                                        |
    | Date-time  | Date-time fields are formatted using the [ISO 8601 standard](https://www.w3.org/TR/NOTE-datetime) for the combined date and time in UTC: `YYYY-MM-DDThh:mm:ss.sssZ`. Example: `2015-09-01T23:59:59.479Z`. |
    | Email | Email fields should follow the [RFC 5322](https://tools.ietf.org/html/rfc5322) standard. Example: `jon.smith@acme.com` |
    | Hex Color | Colors are represented as a string starting with `#` followed by six hexadecimal digits. Each pair of digits represents the intensity of red, green, and blue components respectively. Examples: `#FFFFFF`, `#000000`, `#FF5733`. |
    | Identifier | Identifiers are formatted as a string of 3 alphabetic characters (which represents the type of the identified object), one underscore and 26 alphanumeric characters. Every identifier generated in our system is globally unique. Examples: `acc_44678r08jtm8zbt227tzhc4nw5`, `doc_473cr1y0ghbyc3m1yfbwvn3nxx`. |
    | IP         | IP fields are formatted using the [Internet Protocol version 4 (IPv4)](https://en.wikipedia.org/wiki/Internet_Protocol_version_4) standard: `x.x.x.x` where `x` must be a decimal value between `0` and `255`. Example: `192.158.1.38`. |

    ## Files MIME Types

    The format of the files uploaded must correspond to the MIME type in the `Content-Type` header. See the supported file
    formats and the corresponding MIME types:

    <!-- From: https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types/Common_types -->
    | Extensions | Kind of document | MIME Type |
    | :- | :- | :- |
    | `.csv` | Comma-separated values (CSV) | `text/csv` |
    | `.doc` | Microsoft Word | `application/msword` |
    | `.docx` | Microsoft Word (OpenXML) | `application/vnd.openxmlformats-officedocument.wordprocessingml.document` |
    | `.jpeg`, `.jpg` | JPEG images | `image/jpeg` |
    | `.md` | Markdown | `text/markdown` |
    | `.pdf` | Adobe Portable Document Format (PDF) | `application/pdf` |
    | `.png` | Portable Network Graphics | `image/png` |
    | `.svg` | Scalable Vector Graphics (SVG) | `image/svg+xml` |
    | `.tsv` | Tab-separated values (TSV) | `text/tab-separated-values` |
    | `.txt` | Text (generally ASCII or ISO 8859-n) | `text/plain` |
    | `.xls` | Microsoft Excel | `application/vnd.ms-excel` |
    | `.xlsx` | Microsoft Excel (OpenXML) | `application/vnd.openxmlformats-officedocument.spreadsheetml.sheet` |
servers:
  - url: https://api.getpaid.io
    description: Live
  - url: https://api.sandbox.getpaid.io
    description: Sandbox
security: []
tags:
  - name: Authentication
    description: |
      In order to authenticate with getpaid APIs you need to request an OAuth 2.0 Access Token using your Client ID and Secret
      available from the [getpaid Dashboard](https://dashboard.getpaid.io):

      ```
      curl --location --request POST 'https://auth.getpaid.io/oauth/token' \
      --header 'Content-Type: application/json' \
      --data-raw '{
        "client_id": "{{client_id}}",
        "client_secret": "{{client_secret}}",
        "audience": "https://api.sandbox.getpaid.io",
        "grant_type": "client_credentials"
      }'
      ```

      Specify the appropriate `audience`, `client_id` and `client_secret` to switch between Sandbox and Live environments.
      Full details of the access token endpoint can be found [here](#tag/Authentication/operation/access_token).

      This will return a Bearer access token in the JSON Web Token (JWT) format which you should use in the `Authorization`
      header of any subsequent getpaid API requests:

      ```json
      {
        "access_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c",
        "token_type": "bearer",
        "expires_in": 3600
      }
      ```

      The access token will be valid for the length of time in seconds indicated by the `expires_in` field. When it expires, you should request a new one.
      If using one of our client libraries, this will be handled automatically for you.


      <!-- ReDoc-Inject: <security-definitions> -->
  - name: Accounts
    description: |
      <!-- markdownlint-disable first-line-h1 -->
      An account is the business that will be onboarded to getpaid.
      The account is the main entity that will be used to enable the different capabilities that getpaid offers.

      ## Statuses

      Accounts have a status which indicates its current state. The possible statuses are:

      - `enabled` - The account is active and can be used.
      - `disabled` - The account is inactive and cannot be used.
  - name: Account Links
    description: |
      <!-- markdownlint-disable first-line-h1 -->
      The different relationships that accounts can have with one another. A link can define the hierarchy within the whole company and also allows the assignment of different "roles" that the current account can play in relation to each connected account.

      ## Types

      There are several types of relationships an account can have. The possible ones are:

      - `can_use` - Allows source account to use the resources of destination account.
  - name: Connections
    description: |
      A connection is a link between an account and a third-party service that will be used to enable the different capabilities that getpaid offers.
  - name: Bank Account Authorizations
    description: |
      <!-- markdownlint-disable first-line-h1 -->
      A bank account authorization is a permission granted by a bank account holder, allowing another person or entity to
      access, manage, or perform specific transactions on their account.

      ## Statuses

      Bank account authorizations have a status which indicates the current state of the consent process. The possible
      statuses are:

      - `completed` - The request was completed successfully.
      - `next_step_required` - The request requires additional action before it can be completed.
      - `awaiting` - The request is pending and waiting for a response or action from an external party.
      - `rejected` - The request was rejected by the user/bank.
      - `failed` - The request failed due to technical reasons.

      ## Next Steps

      In a bank account authorization process, there are multiple steps that need to be followed to complete the action. These
      steps are defined by the `next_step` block, which guides the flow of the authorization process.

      Possible values for `next_step.type`:
      <!-- markdownlint-disable link-fragments -->
      - `configure_redirect` - Redirection information needs to be collected by calling [Configure Single Redirect Bank
      Account Authorization](#operation/configure_redirect_account_bank_account_authorizations) endpoint.
      - `redirect` - The user needs to be redirected to the bank's website to complete a required action.
      - `pass_credentials` - The user needs to provide their credentials (e.g., username, password) for authentication
      purposes by calling [Pass User's Credentials Bank Account
      Authorization](#operation/pass_credentials_account_bank_account_authorizations).
      - `select_sca_method` - The user must select a Strong Customer Authentication (SCA) method, such as SMS, app-based
      authentication, or a hardware token by calling [Select SCA Method For Bank Account
      Authorization](#operation/select_sca_method_account_bank_account_authorizations).
      - `pass_sca_code` - The user needs to enter an SCA code (e.g., a one-time password) that was generated from their chosen
      SCA method by calling [Pass SCA Code For Bank Account
      Authorization](#operation/pass_sca_code_account_bank_account_authorizations).
      - `poll` - To poll the consent status, by calling [Get Bank Account
      Authorization](#operation/get_account_bank_account_authorizations), is required in order to determine whether the user
      has successfully authorized the request with the bank. Because the flow occurs directly between the end user and the
      bank without getpaid acting as an intermediary, for example, via a secondary device such as a mobile phone.
      <!-- markdownlint-enable link-fragments -->
  - name: Bank Transactions
    description: |
      A bank transaction is a financial event that occurs when a transfer of funds is made from one party to another.

      In the context of this API, a transaction represents a detailed record of an inbound payment, including direct debit transactions. Each transaction entry provides comprehensive information such as the booking date and time, amount, currency, counterparty details, and payment instrument information. This helps in tracking and managing receivables efficiently, ensuring transparency and accuracy in financial reporting.

      Transactions are essential for maintaining accurate financial records, supporting reconciliation processes, and ensuring that all payments are accounted for correctly. They form the backbone of financial data, enabling businesses to monitor cash flow, manage accounts, and meet regulatory requirements.
  - name: Connections
    description: |
      A connection is a link between an account and a third-party service that will be used to enable the different capabilities that getpaid offers.
  - name: Invoices
    description: |
      <!-- markdownlint-disable first-line-h1 -->
      An invoice is a formal contractual document dispatched from a seller to a buyer, notifying them of the purchase of goods or services and the corresponding obligation to make a payment.

      Additional information regarding the rounding process applied to the calculation of totals and taxes can be found in our [public documentation](../invoices/rounding).

      ## Statuses

      Represents the current status of an invoice.

      - `draft` - The invoice is a draft and can suffer changes.
      - `cancelled` - The invoice has been cancelled.
      - `initiated` - The invoice has been received and is about to be issued.
      - `issued` - The invoice code has been provided or generated.
  - name: Invoice Documents
    description: |
      The generated documents associated to a specific invoice. For example, a PDF.
  - name: Invoices Reports
    description: Export the invoices to a file to get a quick report on the historical data. The available file will be in CSV format.
  - name: Invoices Series
    description: |
      The series are used to create invoices with auto-generated codes. Invoices series can be created only for accounts with `issue_invoices` capability enabled.

      The `prefix` and `suffix` fields are used to generate the invoice number, the `padding` field is used to pad the number with zeros, the `valid_from` and `valid_to` fields are used to define the period in which the series is valid.
      The produced invoices reference will be `{prefix}{padded number}{suffix}`, the length of the reference is limited to 50 characters. So the sum of the length of prefix, suffix and the padding should be less than or equal to 50.
  - name: Invoice Webhooks
    description: |
      Notifications to inform about invoice events that occur so you can take action within your own systems, for example, updating the invoices's state, notifying your customers or integrating with third-parties.
  - name: Payment Instruments
    description: |
      <!-- markdownlint-disable first-line-h1 -->
      A payment instrument represents a financial entity that can be used for processing payments, invoicing, and reconciliation. It contains essential details about the funding source, such as a bank account or other financial methods, and provides metadata related to its status and capabilities.

      Note that every change performed on a payment instrument (create, disable, or enable) will alter the account version and can trigger some verification checks required on any capability.

      ## Statuses

      Payment instruments have a status which indicates its current state. The possible statuses are:

      - `enabled` - The payment instrument is active and can be used.
      - `disabled` - The payment instrument is inactive and cannot be used.
  - name: Subscriptions
    description: A subscription is a recurring invoice that is automatically issued to the buyer to charge for services or products that are delivered on a regular basis.
  - name: Bank Transactions Enrichment
    description: |
      <!-- markdownlint-disable first-line-h1 -->
      Upload bank transactions files to enrich the transactions synchronized with Open Banking.

      ## File Formats

      The supported file formats are:

      | Area | Format | `format` field | Description |
      | :- | :- | :- | :- |
      | Global | ISO 20022 camt.053 | `iso20022_camt053` | Bank to customer cash management in ISO 20022 format. |
      | Spain | AEB43 | `aeb43` | Bank transactions file format used in Spain. |

      ## Statuses

      Bank transactions imports have a status which indicates the current state of the upload process. The possible statuses are:

      - `pending` - The import job has been initiated but the document still to be processed.
      - `validated` - The document format has been validated and it is supported.
      - `completed` - The document has been processed successfully and the transactions were processed and matched, if
      possible.
      <!-- markdownlint-disable-next-line link-fragments -->
      - `error` - The import job failed, check the [status reasons](#tag/Bank-Transactions-Enrichment/Status-Reasons) for
      further details.

      ## Status Reasons

      | Status | Reason Code | Cause | Next Action |
      | :- | :- | :- | :- |
      | `error` | `file_integrity_failed` | The file type is supported but the content does not match the expected format. | Check the uploaded file to validate the format and upload it again with the expected format for the file type. |
      | `error` | `unknown_bank_account` | The bank account of the file does not belong to any of the bank accounts configured in your getpaid account. | Check the configuration of your getpaid account to include the bank account or skip the files related to this bank account. |
      | `error` | `duplicated_file_date` | There is already a file uploaded for the same bank account, format and date. | The file for that date was already uploaded and there is no need of upload it again. |
      | `error` | `missing_open_banking_data` | There are no bank transactions synchronized via Open Banking to be enriched with the uploaded file. | Check the Open Banking configuration of your getpaid account and upload the file again. |
  - name: Chats
    description: |
      A chat is a conversation between a user and the assistant. The assistant is an AI (Artificial Intelligence) prompt that helps the user on his day-by-day tasks within the Getpaid system.

      ## Supported MIME Types

      The format of the files uploaded must correspond to the MIME type in the `Content-Type` header. See the supported file
      formats and the corresponding MIME types:

      <!-- From: https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types/Common_types -->
      | Extensions | Kind of document | MIME Type |
      | :- | :- | :- |
      | `.pdf` | Adobe Portable Document Format (PDF) | `application/pdf` |
      | `.txt` | Text (generally ASCII or ISO 8859-n) | `text/plain` |
  - name: Documents
    description: |
      A document refers to a file that is uploaded to getpaid. It can be a PDF, an image, a CSV, etc. It can serve multiple purposes and it can be uploaded by the customer or getpaid itself.
      Based on the type of document, there are different requirements on size and format and scopes required to upload the document.

      ## File types and validations

      The following table describes the allowed file types, their MIME types, and the maximum size allowed for each document type. The table also indicates the additional scopes required to upload each type of document.

      | Document Type       | Allowed MIME Types                         | Max Size | Additional scopes required for uploading | Additional scopes required for reading |
      |---------------------|--------------------------------------------|----------|------------------------------------------|----------------------------------------|
      | `company_logo`        | `image/jpeg`, `image/png`, `image/svg+xml` | 512KB    | `accounts:read_write`                    | `accounts:read` or `accounts:read_write` |
      | `invoice_attachment`  | [all supported mime types](/api#section/Introduction/Files-MIME-Types)         | 2MB      | `invoices:read_write`                    | `invoices:read` or `invoices:read_write` |
      | `data_enrichment`     | `text/xml`, `text/plain`                   | 2MB      | `bank_transactions:read_write`           | `bank_transactions:read` or `bank_transactions:read_write` |
  - name: Labels
    description: |
      Labels are used to categorize and organize your data. They can be used to group invoices, accounts, or any other entity in the system.
paths:
  /oauth/token:
    post:
      tags:
        - Authentication
      summary: Access Token
      description: Obtain an OAuth 2.0 Access token to authenticate API requests
      operationId: access_token
      servers:
        - url: https://auth.getpaid.io
          description: OAuth Server
  /v2alpha1/accounts:
    post:
      tags:
        - Accounts
      summary: Create Account
      operationId: create_account
      security:
        - OAuth:
            - accounts:read_write
    get:
      tags:
        - Accounts
      summary: List Accounts
      operationId: list_accounts
      security:
        - OAuth:
            - accounts:read
        - OAuth:
            - accounts:read_write
  /v2alpha1/accounts/{account_id}:
    get:
      tags:
        - Accounts
      summary: Get Account
      description: |
        Gets an account associated to the owner account.
      operationId: get_account
      security:
        - OAuth:
            - accounts:read
        - OAuth:
            - accounts:read_write
    patch:
      tags:
        - Accounts
      summary: Update Account
      description: |
        It applies partial modifications to an existing account. On this way, every field that is not provided will remain unchanged,
        and all the provided ones would be updated in our system. Please note that some fields might require some attention and can raise some
        additional checks required by any capability requirement.
      operationId: update_account
      security:
        - OAuth:
            - accounts:read_write
  /v2alpha1/accounts/{account_id}/disable:
    post:
      tags:
        - Accounts
      summary: Disable Account
      description: It disables an existing account. Once an account is disabled, it will not be accessible anymore.
      operationId: disable_account
      security:
        - OAuth:
            - accounts:read_write
  /v2alpha1/accounts/{account_id}/taxes:
    get:
      tags:
        - Taxes
      summary: List Taxes
      description: |
        List taxes associated to a specific account.
      operationId: list_account_taxes
      security:
        - OAuth:
            - accounts:read
            - accounts:read_write
  /v2alpha1/accounts/bank_account_authorizations:
    post:
      tags:
        - Bank Account Authorizations
      summary: Create Bank Account Authorization
      description: |
        Creates a bank account authorizations associated to a specific account.
      operationId: create_account_bank_account_authorizations
      security:
        - OAuth:
            - bank_account_authorizations:read_write
  /v2alpha1/accounts/bank_account_authorizations/{bank_account_authorization_id}:
    get:
      tags:
        - Bank Account Authorizations
      summary: Get Bank Account Authorization
      description: |
        Gets a bank account authorizations associated to a specific account.
      operationId: get_account_bank_account_authorizations
      security:
        - OAuth:
            - bank_account_authorizations:read_write
    delete:
      tags:
        - Bank Account Authorizations
      summary: Revoke Bank Account Authorization
      description: |
        Revokes the authorization associated with a specific bank account.
        Once an authorization is revoked, it cannot be re-enabled. A new authorization must be obtained to regain access.
      operationId: revoke_account_bank_account_authorizations
      security:
        - OAuth:
            - bank_account_authorizations:read_write
  /v2alpha1/accounts/bank_account_authorizations/{bank_account_authorization_id}/configure_redirect:
    post:
      tags:
        - Bank Account Authorizations
      summary: Configure Single Redirect Bank Account Authorization
      description: |
        Configure the authorization process to redirect the user to the provided URL.
      operationId: configure_redirect_account_bank_account_authorizations
      security:
        - OAuth:
            - bank_account_authorizations:read_write
  /v2alpha1/accounts/bank_account_authorizations/{bank_account_authorization_id}/pass_credentials:
    post:
      tags:
        - Bank Account Authorizations
      summary: Pass User's Credentials Bank Account Authorization
      description: |
        Capture the user's credentials to allow them to login.
      operationId: pass_credentials_account_bank_account_authorizations
      security:
        - OAuth:
            - bank_account_authorizations:read_write
  /v2alpha1/accounts/bank_account_authorizations/{bank_account_authorization_id}/select_sca_method:
    post:
      tags:
        - Bank Account Authorizations
      summary: Select SCA Method For Bank Account Authorization
      description: |
        Select SCA method to receive a SCA code.
      operationId: select_sca_method_account_bank_account_authorizations
      security:
        - OAuth:
            - bank_account_authorizations:read_write
  /v2alpha1/accounts/bank_account_authorizations/{bank_account_authorization_id}/pass_sca_code:
    post:
      tags:
        - Bank Account Authorizations
      summary: Pass SCA Code For Bank Account Authorization
      description: |
        Pass SCA code to complete the authorization.
      operationId: pass_sca_code_account_bank_account_authorizations
      security:
        - OAuth:
            - bank_account_authorizations:read_write
  /v2alpha1/accounts/{account_id}/invoices_series:
    post:
      tags:
        - Invoices Series
      summary: Create Invoices Series
      description: |
        Creates new invoices series for the account.
      operationId: create_invoices_series
      security:
        - OAuth:
            - accounts:read_write
    get:
      tags:
        - Invoices Series
      summary: List Invoices Series
      description: |
        Lists the existing invoices series.
      operationId: list_invoices_series
      security:
        - OAuth:
            - accounts:read
        - OAuth:
            - accounts:read_write
  /v2alpha1/accounts/{account_id}/invoices_series/{invoices_series_id}:
    get:
      tags:
        - Invoices Series
      summary: Get Invoices Series
      description: |
        Gets the invoices series details.
      operationId: get_invoices_series
      security:
        - OAuth:
            - accounts:read
        - OAuth:
            - accounts:read_write
  /v2alpha1/account_links:
    post:
      tags:
        - Account Links
      summary: Create Account Link
      operationId: create_account_link
      security:
        - OAuth:
            - accounts:read_write
    get:
      tags:
        - Account Links
      summary: List Account Links
      operationId: list_account_links
      security:
        - OAuth:
            - accounts:read
        - OAuth:
            - accounts:read_write
  /v2alpha1/account_links/{account_link_id}:
    get:
      tags:
        - Account Links
      summary: Get Account Link
      description: |
        Gets an account link associated to the owner account.
      operationId: get_account_link
      security:
        - OAuth:
            - accounts:read
        - OAuth:
            - accounts:read_write
    delete:
      tags:
        - Account Links
      summary: Delete Account Link
      description: |
        Deletes an account link associated to the owner account.
      operationId: delete_account_link
      security:
        - OAuth:
            - accounts:read_write
  /v2alpha1/bank_transactions:
    get:
      tags:
        - Bank Transactions
      summary: List Bank Transactions
      operationId: list_bank_transactions
      security:
        - OAuth:
            - bank_transactions:read
  /v2alpha1/bank_transactions/documents:
    post:
      tags:
        - Bank Transactions Enrichment
      summary: Upload Bank Transactions File
      description: |
        Upload a bank file to enrich the transactions extracted from the Open Banking connection.

        After the upload the file must be imported using the [Import Bank Transactions File](#operation/import_bank_transactions) endpoint.

        See the [file formats supported](#tag/Bank-Transactions-Enrichment/File-Formats) for the bank transactions files.
      operationId: upload_bank_transactions_document
      security:
        - OAuth:
            - bank_transactions:read_write
  /v2alpha1/bank_transactions/imports:
    post:
      tags:
        - Bank Transactions Enrichment
      summary: Import Bank Transactions File
      description: |
        Import a bank transactions file to enrich bank transactions.

        The file must be uploaded using the [Upload Bank Transactions File](#operation/upload_bank_transactions_document) endpoint.
      operationId: import_bank_transactions
      security:
        - OAuth:
            - bank_transactions:read_write
    get:
      tags:
        - Bank Transactions Enrichment
      summary: List Bank Import Jobs
      description: |
        Get the status of all the bank transactions files import jobs ordered by uploaded time in descending order.

        The import process is initiated using the [Upload Bank Transactions File](#operation/upload_bank_transactions_document) endpoint.
      operationId: list_bank_transactions_imports
      security:
        - OAuth:
            - bank_transactions:read
        - OAuth:
            - bank_transactions:read_write
  /v2alpha1/bank_transactions/imports/{import_id}:
    get:
      tags:
        - Bank Transactions Enrichment
      summary: Get Bank Import Status
      description: |
        Get the status of an asynchronous import job.

        The import process is initiated using the [Upload Bank Transactions File](#operation/upload_bank_transactions_document) endpoint.
      operationId: get_bank_transactions_import
      security:
        - OAuth:
            - bank_transactions:read
        - OAuth:
            - bank_transactions:read_write
  /v2alpha1/invoices:
    post:
      tags:
        - Invoices
      summary: Create Invoice
      operationId: create_invoice
      security:
        - OAuth:
            - invoices:read_write
    get:
      tags:
        - Invoices
      summary: List Invoices
      operationId: list_invoices
      security:
        - OAuth:
            - invoices:read
  /v2alpha1/invoices/{invoice_id}:
    get:
      tags:
        - Invoices
      summary: Get Invoice
      operationId: get_invoice
      security:
        - OAuth:
            - invoices:read
    put:
      tags:
        - Invoices
      summary: Update Draft Invoice
      description: Updates an invoice. Only invoices on status `draft` can be updated.
      operationId: update_invoice
      security:
        - OAuth:
            - invoices:read_write
  /v2alpha1/invoices/{invoice_id}/issue:
    post:
      tags:
        - Invoices
      summary: Issue Draft Invoice
      description: It issues a draft invoice. Please note that this operation is allowed only if the related infoice is in `draft` status.
      operationId: issue_draft_invoice
      security:
        - OAuth:
            - invoices:read_write
  /v2alpha1/invoices/{invoice_id}/cancel:
    post:
      tags:
        - Invoices
      summary: Cancel Draft Invoice
      description: It cancels a draft invoice. Please note that this operation is allowed only if the related infoice is in `draft` status.
      operationId: cancel_draft_invoice
      security:
        - OAuth:
            - invoices:read_write
  /v2alpha1/invoices/exports:
    post:
      tags:
        - Invoices Reports
      summary: Export Invoices
      description: |
        Request to export to a file a list of invoices with the specified filters.

        The export process is asynchronous. The response will contain the export unique identifier that can be used to check the status of the job using the [Get Invoices Export Status](#operation/get_invoices_export) endpoint.

        When the export is completed, the report file will be available for download at the URL provided in the response using [Get Invoice Report](#operation/get_invoices_report) endpoint.
      operationId: export_invoices
      security:
        - OAuth:
            - invoices:read
        - OAuth:
            - invoices:read_write
  /v2alpha1/invoices/exports/{export_id}:
    get:
      tags:
        - Invoices Reports
      summary: Get Invoices Export Status
      description: |
        Get the status of an asynchronous export job.

        The export process can be initiated using the [Export Invoices](#operation/export_invoices) endpoint.
      operationId: get_invoices_export
      security:
        - OAuth:
            - invoices:read
        - OAuth:
            - invoices:read_write
  /v2alpha1/invoices/reports/{report_id}:
    get:
      tags:
        - Invoices Reports
      summary: Get Invoices Report
      description: Download the invoices report as a result of the export job. Check the status of the export job using the [Get Invoices Export Status](#operation/get_invoices_export) endpoint.
      operationId: get_invoices_report
      security:
        - OAuth:
            - invoices:read
        - OAuth:
            - invoices:read_write
  /v2alpha1/invoices/documents:
    post:
      tags:
        - Invoice Documents
      summary: Upload Invoice Document
      description: |
        Upload an additional document to be attached to an invoice.

        After uploading the document, it can be linked to the invoice using the `id` of the document from the response in the [Create Invoice](#operation/create_invoice) endpoint.

        The format of the document uploaded must correspond to the MIME type in the `Content-Type` header. See the [corresponding MIME types to each kind of document](#section/Introduction/Files-MIME-Types).
      operationId: upload_invoice_document
      security:
        - OAuth:
            - invoices:read_write
  /v2alpha1/invoices/{invoice_id}/documents/{document_id}:
    get:
      tags:
        - Invoice Documents
      summary: Get Invoice Document
      operationId: get_invoice_document
      description: |
        Downloads a document related to an invoice.

        The document can be a file generated with the invoice data or a file uploaded by the user.
      security:
        - OAuth:
            - invoices:read
        - OAuth:
            - invoices:read_write
  /v2alpha1/subscriptions:
    post:
      tags:
        - Subscriptions
      summary: Create Subscription
      description: |
        Create a subscription. All dates are to be considered in the seller's timezone.
      operationId: create_subscription
      security:
        - OAuth:
            - invoices:read_write
    get:
      tags:
        - Subscriptions
      summary: List Subscriptions
      description: List the existing subscriptions.
      operationId: list_subscriptions
      security:
        - OAuth:
            - invoices:read
        - OAuth:
            - invoices:read_write
  /v2alpha1/subscriptions/{subscription_id}:
    patch:
      tags:
        - Subscriptions
      summary: Update Subscription
      description: |
        Update a subscription. Buyer, seller and billing cycle cannot be updated. The updated subscription can be configured to be effective at a future date.
        If not provided, the update will take effect on the next issued invoice. The new configuration will replace the existing one. All dates are to be considered in the seller's timezone.
      operationId: update_subscription
      security:
        - OAuth:
            - invoices:read_write
    get:
      tags:
        - Subscriptions
      summary: Get Subscription
      description: Get the subscription details.
      operationId: get_subscription
      security:
        - OAuth:
            - invoices:read
        - OAuth:
            - invoices:read_write
  /v2alpha1/subscriptions/{subscription_id}/billing_cycles:
    get:
      tags:
        - Subscriptions
      summary: List Subscription Billing Cycles
      description: Get the subscription billing cycles.
      operationId: list_subscription_billing_cycles
      security:
        - OAuth:
            - invoices:read
        - OAuth:
            - invoices:read_write
  /v2alpha1/subscriptions/{subscription_id}/cancel:
    post:
      tags:
        - Subscriptions
      summary: Cancel Subscription
      description: |
        Cancel a subscription at the end of the given billing cycle. If not provided the subscription will be canceled at the end of the current billing cycle.
      operationId: cancel_subscription
      security:
        - OAuth:
            - invoices:read_write
  /v2alpha1/labels:
    post:
      tags:
        - Labels
      summary: Create Label
      operationId: create_label
      security:
        - OAuth:
            - accounts:read_write
    get:
      tags:
        - Labels
      summary: List Labels
      operationId: list_labels
      security:
        - OAuth:
            - accounts:read
        - OAuth:
            - accounts:read_write
  /v2alpha1/labels/{label_id}:
    get:
      tags:
        - Labels
      summary: Get Label
      operationId: get_label
      security:
        - OAuth:
            - accounts:read_write
        - OAuth:
            - accounts:read
    put:
      tags:
        - Labels
      summary: Update Label
      operationId: update_label
      security:
        - OAuth:
            - accounts:read_write
    delete:
      tags:
        - Labels
      summary: Delete Label
      operationId: delete_label
      security:
        - OAuth:
            - accounts:read_write
  /v2alpha1/payment_advices/{payment_advice_id}:
    get:
      tags:
        - Payment Advices
      summary: Get Payment Advice
      operationId: get_payment_advice
      security:
        - OAuth:
            - invoices:read
  /v2alpha1/payment_advices/{payment_advice_id}/documents/{document_id}:
    get:
      tags:
        - Payment Advice Documents
      summary: Get Payment Advice Document
      operationId: get_payment_advice_document
      description: |
        Retrieves and downloads an attached document associated with a specific payment advice.
      security:
        - OAuth:
            - invoices:read
        - OAuth:
            - invoices:read_write
  /v2alpha1/payment_instruments:
    post:
      tags:
        - Payment Instruments
      summary: Create Payment Instument
      operationId: create_payment_instrument
      security:
        - OAuth:
            - accounts:read_write
    get:
      tags:
        - Payment Instruments
      summary: List Payment Instruments
      description: |
        List payment instruments associated the specified accounts.
      operationId: list_account_payment_instruments
      security:
        - OAuth:
            - accounts:read
        - OAuth:
            - accounts:read_write
  /v2alpha1/payment_instruments/{payment_instrument_id}:
    get:
      tags:
        - Payment Instruments
      summary: Get Payment Instrument
      description: |
        Gets a payment instrument associated to the owner account.
      operationId: get_payment_instrument
      security:
        - OAuth:
            - accounts:read
        - OAuth:
            - accounts:read_write
  /v2alpha1/payment_instruments/{payment_instrument_id}/disable:
    post:
      tags:
        - Payment Instruments
      summary: Disable Payment Instrument
      description: It disables an existing payment instrument.
      operationId: disable_payment_instrument
      security:
        - OAuth:
            - accounts:read_write
  /v2alpha1/payment_instruments/{payment_instrument_id}/enable:
    post:
      tags:
        - Payment Instruments
      summary: Enable Payment Instrument
      description: It enables a disabled payment instrument.
      operationId: enable_payment_instrument
      security:
        - OAuth:
            - accounts:read_write
  /v2alpha1/payment_terms:
    get:
      tags:
        - Payment Terms
      summary: List Payment Terms
      operationId: list_payment_terms
      security:
        - OAuth:
            - payment_terms:read
  /v2alpha1/payment_terms/{payment_term_id}:
    get:
      tags:
        - Payment Terms
      summary: Get Payment Term
      operationId: get_payment_term
      security:
        - OAuth:
            - payment_terms:read
  /v2alpha1/payment_terms/{payment_term_id}/transactions/{transaction_id}/confirm:
    post:
      tags:
        - Payment Terms
      summary: Confirm Payment Term Match
      operationId: confirm_payment_term_match
      security:
        - OAuth:
            - payment_terms:read_write
  /v2alpha1/payment_terms/{payment_term_id}/transactions/{transaction_id}/reject:
    post:
      tags:
        - Payment Terms
      summary: Reject Payment Term Match
      operationId: reject_payment_term_match
      security:
        - OAuth:
            - payment_terms:read_write
  /v2alpha1/templates/{template_type}/{template_id}/preview:
    post:
      tags:
        - Templates
      summary: Preview Template
      operationId: preview_template
      security:
        - OAuth:
            - accounts:read
        - OAuth:
            - accounts:read_write
  /v2alpha1/templates/{template_type}/{template_id}:
    get:
      tags:
        - Templates
      summary: Get Default Template
      operationId: get_default_template
      security:
        - OAuth:
            - accounts:read
        - OAuth:
            - accounts:read_write
  /v2alpha1/chats:
    post:
      tags:
        - Chats
      summary: Create Chat
      description: Creates a chat to interact with the AI assistant.
      operationId: create_chat
      security:
        - OAuth:
            - chats:read_write
    get:
      tags:
        - Chats
      summary: List Chats
      description: Gets a list of chats.
      operationId: list_chats
      security:
        - OAuth:
            - chats:read_write
  /v2alpha1/chats/{chat_id}/messages:
    get:
      tags:
        - Chats
      summary: List Messages
      description: Gets a list of messages related to a specific chat.
      operationId: list_chat_messages
      security:
        - OAuth:
            - chats:read_write
    post:
      tags:
        - Chats
      summary: Send Message
      description: Sends a message to a the chat.
      operationId: send_chat_message
      security:
        - OAuth:
            - chats:read_write
  /v2alpha1/chats/{chat_id}/documents:
    post:
      tags:
        - Chats
      summary: Upload Chat Document
      description: |
        Upload a document to be attached to a chat. Please check the [supported MIME types](#tag/Chats/Supported-MIME-Types).
      operationId: upload_chat_document
      security:
        - OAuth:
            - chats:read_write
  /v2alpha1/documents:
    post:
      tags:
        - Documents
      summary: Upload Document
      description: |
        Upload a Document.
      operationId: upload_document
      security:
        - OAuth:
            - documents:read_write
  /v2alpha1/documents/{document_id}:
    get:
      tags:
        - Documents
      summary: Get Document
      description: |
        Get document returns the metadata of the document without its content.
      operationId: get_document
      security:
        - OAuth:
            - documents:read
  /v2alpha1/documents/{document_id}/content:
    get:
      tags:
        - Documents
      summary: Download Document
      description: |
        Download document content.
      operationId: download_document_content
      security:
        - OAuth:
            - documents:read
webhooks:
  invoice_draft_document_updated:
    post:
      summary: Invoice Draft Document Updated
      operationId: invoice_draft_document_updated
      description: The `invoice_draft_document_updated` webhook is sent when the invoice document is generated for a draft invoice.
      tags:
        - Invoice Webhooks
  invoice_issued:
    post:
      summary: Invoice Issued
      operationId: invoice_issued
      description: |
        The `invoice_issued` webhook is sent when an invoice is issued: right after creation when the invoice is created with a provided code or when the code is generated if it is based on a series.
      tags:
        - Invoice Webhooks
  invoice_document_created:
    post:
      summary: Invoice Document Created
      operationId: invoice_document_created
      description: |
        The `invoice_document_created` webhook is sent when the invoice document is generated.
      tags:
        - Invoice Webhooks
  invoice_buyer_notification_sent:
    post:
      summary: Invoice Buyer Notification Sent
      operationId: invoice_buyer_notification_sent
      description: |
        The `invoice_buyer_notification_sent` webhook is sent when the invoice notification is sent to the buyer.
      tags:
        - Invoice Webhooks
  invoice_match_suggested:
    post:
      summary: Invoice Match Suggested
      operationId: invoice_match_suggested
      description: |
        The `invoice_match_suggested` webhook is sent when a bank transaction has been suggested to match an invoice.
      tags:
        - Invoice Webhooks
  bank_transaction_import_completed:
    post:
      summary: Bank Transactions Import Completed
      operationId: bank_transactions_import_completed
      description: |
        The `bank_transactions_import_completed` webhook is triggered when a bank transaction import is completed.
      tags:
        - Bank Transactions Enrichment Webhooks
  bank_transaction_import_error:
    post:
      summary: Bank Transactions Import Error
      operationId: bank_transactions_import_error
      description: |
        The `bank_transactions_import_error` webhook is triggered when a bank transaction import has failed.
      tags:
        - Bank Transactions Enrichment Webhooks
  bank_transaction_import_validated:
    post:
      summary: Bank Transactions Import Validated
      operationId: bank_transactions_import_validated
      description: |
        The `bank_transactions_import_validated` webhook is triggered when a bank transaction import is validated.
      tags:
        - Bank Transactions Enrichment Webhooks
components:
  securitySchemes:
    OAuth:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: https://auth.getpaid.io/oauth/token
          scopes:
            accounts:read: Allows to read accounts.
            accounts:read_write: Allows to read and/or upsert accounts.
            bank_account_authorizations:read_write: Allows to read and/or create bank account authorizations.
            bank_transactions:read: Allows to read bank transactions.
            bank_transactions:read_write: Allows to read and/or upsert bank transactions.
            documents:read: Allows to read documents.
            documents:read_write: Allows to read and/or upload documents.
            invoices:read: Allows to read invoices.
            invoices:read_write: Allows to read and/or upsert invoices.
            payment_terms:read: Allows to read payment terms.
            payment_terms:read_write: Allows to read and/or upsert payment terms.
            chats:read_write: Allows to read and/or upsert chats.
x-tagGroups:
  - name: General
    tags:
      - Authentication
  - name: Accounts
    tags:
      - Accounts
      - Account Links
      - Bank Account Authorizations
      - Invoices Series
      - Labels
      - Payment Instruments
      - Taxes
  - name: Documents
    tags:
      - Documents
  - name: Invoicing
    tags:
      - Invoices
      - Invoice Documents
      - Invoices Reports
      - Invoice Webhooks
  - name: Subscriptions
    tags:
      - Subscriptions
  - name: Reconciliation
    tags:
      - Bank Transactions
      - Bank Transactions Enrichment
      - Bank Transactions Enrichment Webhooks
      - Payment Advices
      - Payment Advice Documents
      - Payment Terms
  - name: Templates
    tags:
      - Templates
